version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "55432:5432"  # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

  backend:
    build: .
    container_name: backend
    command: sh -c "npx drizzle-kit generate --config=drizzle.config.ts && npx drizzle-kit push --config=drizzle.config.ts && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      PORT: 4000        # <-- le backend écoute sur ce port
    depends_on:
      - postgres
    ports:
      - "4000:4000"     # <-- expose ce port sur la machine hôte

volumes:
  postgres_data:
