version: "3.8"

services:
  polymarket_sport:
    build: .
    container_name: polymarket-sure-win
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run launch
