/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reselTSol from "./ReselT.sol";
export type { reselTSol };
export type { EventFactory } from "./EventFactory";
export type { EventTicket } from "./EventTicket";
